import { useEffect,useState } from "react";
import { Container,btnClass,inputClass } from "@/components/ui";
import { Logo,Icon } from "@/components/Icon";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { navigate } from "@/lib/router";

export function SellerLogin(){const {user,refresh}=useAuth();const [email,setEmail]=useState("");const [phone,setPhone]=useState("");const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [token,setToken]=useState(""); const [premiumPhone,setPremiumPhone]=useState(""); const [premiumBusy,setPremiumBusy]=useState(false); const [premiumMsg,setPremiumMsg]=useState("");
useEffect(()=>{const q=new URLSearchParams(location.hash.split("?")[1]||"");const t=q.get("token");if(t){setToken(t);void (async()=>{try{await api.verifyMagic(t);await refresh();navigate("/dashboard")}catch(e){setError(e instanceof Error?e.message:"Login link is invalid")}})()}},[refresh]);
if(user)return <section className="min-h-screen bg-mint/50 pt-32"><Container className="max-w-lg"><div className="rounded-3xl bg-white p-8 text-center"><h1 className="text-3xl text-deep">You are already signed in</h1><button className={btnClass("gold","lg","mt-6 w-full")} onClick={()=>navigate(user.role==="ADMIN"?"/admin":"/dashboard")}>Open dashboard</button></div></Container></section>;
const send=async()=>{setError("");if(!email && !phone){setError("Enter your email or phone number.");return}setBusy(true);try{const r=await api.requestMagic({email:email||undefined,phone:phone||undefined,intent:"seller"});setSent(true);if(r.devLink) console.info("Development magic link:",r.devLink)}catch(e){setError(e instanceof Error?e.message:"Could not send login link")}finally{setBusy(false)}};
return <section className="min-h-screen brand-gradient pb-20 pt-28 text-white"><Container className="max-w-5xl"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><Logo tone="light"/><p className="mt-6 text-gold font-extrabold uppercase tracking-[.16em] text-xs">Secure Premium Seller Access</p><h1 className="mt-4 text-4xl sm:text-5xl">Your store. Your earnings. <span className="text-gold">Your control.</span></h1><p className="mt-5 max-w-lg text-white/70">Use a one-time magic link. No reusable password is stored. Premium status, products, orders, balances and payouts are verified server-side.</p></div><div className="rounded-[32px] bg-white p-7 text-ink shadow-2xl"><h2 className="text-2xl text-deep">Seller Magic Login</h2>{!sent?<><p className="mt-2 text-sm text-forest/70">We will send a one-time secure login link.</p><label className="mt-6 block text-sm font-bold text-deep">Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com" className={inputClass+" mt-2"}/><div className="my-4 text-center text-xs font-bold text-forest/45">OR</div><label className="block text-sm font-bold text-deep">Phone</label><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="0712345678" className={inputClass+" mt-2"}/>{error&&<p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}<button disabled={busy} onClick={send} className={btnClass("gold","lg","mt-6 w-full")}>{busy?"Sending…":"Send secure login link"}<Icon name="key" className="h-5 w-5"/></button></>:<div className="mt-6 rounded-2xl bg-mint p-5"><p className="font-extrabold text-deep">Check your email or phone</p><p className="mt-2 text-sm text-forest/70">The link expires in 15 minutes and can only be used once.</p>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button className={btnClass("outline","md","mt-5 w-full")} onClick={()=>setSent(false)}>Use another identity</button></div>}</div></div></Container></section>}
