import {useEffect,useMemo,useState} from "react";
import {Container,Field,btnClass,inputClass} from "@/components/ui";
import {Icon} from "@/components/Icon";
import {CATEGORIES_BY_TYPE,PRODUCT_TYPES,ProductType} from "@/lib/data";
import {api} from "@/lib/api";
import {useAuth} from "@/lib/auth";

const STEPS=["Choose Type","Product Details","Set Price","Payment","Magic Link"];
export function SellToday(){
 const {user,loading,refresh}=useAuth(); const [step,setStep]=useState(1),[kind,setKind]=useState<ProductType|"">(""),[name,setName]=useState(""),[description,setDescription]=useState(""),[category,setCategory]=useState(""),[price,setPrice]=useState(""),[handle,setHandle]=useState(""),[paymentNumber,setPaymentNumber]=useState(""),[identity,setIdentity]=useState(""),[magicSent,setMagicSent]=useState(false),[file,setFile]=useState<File|null>(null),[cover,setCover]=useState<File|null>(null),[delivery,setDelivery]=useState(""),[inventory,setInventory]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[created,setCreated]=useState<any>(null),[copied,setCopied]=useState(false);
 const selectedType=useMemo(()=>PRODUCT_TYPES.find(t=>t.value===kind),[kind]);
 const availableCategories=useMemo(()=>kind?CATEGORIES_BY_TYPE[kind]:[],[kind]);
 useEffect(()=>{if(!user||user.role!=="SELLER")return;api.sellerDashboard().then((r:any)=>{setHandle(r?.seller?.handle||"");setPaymentNumber(r?.seller?.paymentNumber||"")}).catch(()=>{})},[user]);
 useEffect(()=>{const q=window.location.hash.split("?")[1],token=q&&new URLSearchParams(q).get("token");if(!token)return;(async()=>{try{setBusy(true);await api.verifyMagic(token);if(!(await refresh()))throw new Error("Magic Link verified, but seller access could not be created.");window.history.replaceState(null,"",window.location.pathname+"#/sell");setStep(4)}catch(e){setError(e instanceof Error?e.message:"Invalid or expired Magic Link.")}finally{setBusy(false)}})()},[refresh]);
 const chooseType=(value:ProductType)=>{setKind(value);setCategory("");setFile(null);setInventory("");setError("");setStep(2)};
 const next=()=>{setError("");if(step===1&&!kind)return setError("Choose what you are selling.");if(step===2&&(name.trim().length<3||description.trim().length<12||!category))return setError("Complete the product name, description and category.");if(step===2&&kind==="Digital Product"&&!file)return setError("Upload the digital file you are selling.");if(step===3&&Number(price)<50)return setError("Set a price of at least KSh 50.");setStep(s=>Math.min(5,s+1))};
 const sendMagic=async()=>{if(!identity.trim())return setError("Enter your email or phone number.");setBusy(true);try{await api.requestMagic(identity.includes("@")?{email:identity.trim(),intent:"seller"}:{phone:identity.replace(/\D/g,""),intent:"seller"});setMagicSent(true)}catch(e){setError(e instanceof Error?e.message:"Could not create seller access.")}finally{setBusy(false)}};
 const save=async()=>{setError("");const phone=paymentNumber.replace(/\D/g,"");if(!/^(07\d{8}|01\d{8})$/.test(phone))return setError("Enter a valid Kenyan M-Pesa number.");if(!/^[a-z0-9_]{3,30}$/.test(handle))return setError("Seller handle must be 3–30 characters.");setBusy(true);try{await api.sellerProfile({handle,paymentNumber:phone});setStep(5)}catch(e){setError(e instanceof Error?e.message:"Could not save seller details.")}finally{setBusy(false)}};
 const publish=async()=>{if(!user||user.role!=="SELLER")return setError("Seller authentication is required.");setBusy(true);try{const fd=new FormData();fd.append("name",name.trim());fd.append("description",description.trim());fd.append("category",category);fd.append("kind",kind);fd.append("priceCents",String(Math.round(Number(price)*100)));fd.append("deliveryText",delivery);if(inventory)fd.append("inventory",inventory);if(kind==="Digital Product"){fd.append("instant","true");fd.append("downloadLimit","5");fd.append("expiresHours","72")}if(file)fd.append("file",file);if(cover)fd.append("cover",cover);const r=await api.createProduct(fd);setCreated(r.product);setCopied(false)}catch(e){setError(e instanceof Error?e.message:"Could not create your product.")}finally{setBusy(false)}};
 const copyLink=async(link:string)=>{try{await navigator.clipboard.writeText(link);setCopied(true)}catch{setError("Could not copy automatically. Select the link and copy it manually.")}};
 if(loading)return <section className="min-h-screen bg-mint/40 pt-32"><Container className="text-center">Loading UzaLink…</Container></section>;
 if(created){const link=location.origin+"/#/magic/"+created.code;return <section className="min-h-screen bg-mint/40 pb-20 pt-28"><Container className="max-w-2xl"><div className="rounded-[32px] bg-white p-8 text-center shadow-sm"><Icon name="checkCircle" className="mx-auto h-16 w-16 text-brand"/><p className="mt-5 text-xs font-extrabold uppercase tracking-[.16em] text-brand">Your Magic Link is ready</p><h1 className="mt-3 text-4xl text-deep">{created.name}</h1><p className="mt-3 text-forest/65">Your link is displayed below. Copy it and share it anywhere you want. Nothing is sent automatically by email or SMS.</p><div className="mt-6 break-all rounded-2xl bg-mint p-4 text-left font-mono text-sm select-all">{link}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button className={btnClass("deep","lg")} onClick={()=>copyLink(link)}>{copied?"Copied ✓":"Copy Magic Link"}</button><button className={btnClass("gold","lg")} onClick={()=>location.reload()}>Create Another Product</button></div></div></Container></section>}
 return <section className="min-h-screen bg-mint/40 pb-24 pt-28"><Container className="max-w-5xl"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">Sell today</p><h1 className="mt-4 text-4xl text-deep sm:text-5xl">Create Your Product.<br/>Get Your Magic Link.</h1><p className="mt-4 text-[16px] leading-relaxed text-forest/65">Create your product, set your price, add your M-Pesa number and get your Magic Link. Free sellers finish here. Premium seller dashboard access is KSh 1,000/month.</p></div>
 <div className="mt-8 rounded-[32px] border border-forest/10 bg-white p-5 shadow-sm sm:p-8"><div className="grid grid-cols-5 gap-2">{STEPS.map((x,i)=><button type="button" key={x} disabled={i+1>step} onClick={()=>i+1<=step&&setStep(i+1)} className="text-left"><div className={i+1<=step?"h-2 rounded-full bg-brand":"h-2 rounded-full bg-forest/10"}/><p className="mt-2 truncate text-[11px] font-bold text-forest/50">{i+1} {x}</p></button>)}</div>
 {step===1&&<div className="mt-8"><h2 className="text-3xl text-deep">What are you selling?</h2><p className="mt-2 text-forest/60">Choose the option that best describes your offer. Your category choices will be synchronized to this selection.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{PRODUCT_TYPES.map(t=><button type="button" key={t.value} onClick={()=>chooseType(t.value)} className={"rounded-2xl border p-5 text-left "+(kind===t.value?"border-brand bg-mint":"border-forest/10 hover:border-brand/40")}><p className="font-extrabold text-deep">{t.label}</p><p className="mt-1 text-xs text-forest/55">{t.blurb}</p></button>)}</div></div>}
 {step===2&&<div className="mt-8 grid gap-5"><div className="rounded-2xl bg-mint p-4"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">Selected offer</p><p className="mt-1 font-extrabold text-deep">{selectedType?.label}</p><p className="text-sm text-forest/60">Categories below are filtered specifically for this offer type.</p></div><h2 className="text-3xl text-deep">Product Details</h2><Field label="Product or offer name"><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Business Starter Kit" className={inputClass}/></Field><Field label="Description"><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={5} placeholder="Tell customers what they get." className={inputClass}/></Field><Field label="Category"><select value={category} onChange={e=>setCategory(e.target.value)} className={inputClass}><option value="">Choose a category for {selectedType?.label}</option>{availableCategories.map(c=><option key={c}>{c}</option>)}</select></Field>{kind==="Digital Product"&&<><Field label="Digital file"><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)} className={inputClass}/></Field><Field label="Cover image (optional)"><input type="file" accept="image/*" onChange={e=>setCover(e.target.files?.[0]||null)} className={inputClass}/></Field></>}{kind==="Physical Product"&&<Field label="Inventory (optional)"><input value={inventory} onChange={e=>setInventory(e.target.value.replace(/\D/g,""))} className={inputClass}/></Field>}<Field label="Fulfillment / delivery details"><input value={delivery} onChange={e=>setDelivery(e.target.value)} placeholder="Delivery, appointment or access details" className={inputClass}/></Field></div>}
 {step===3&&<div className="mt-8 max-w-2xl"><h2 className="text-3xl text-deep">Set Price</h2><p className="mt-2 text-forest/60">Customers pay in Kenyan shillings. UzaLink keeps 5% and your seller balance receives 95%.</p><Field label="Price (KSh)"><input value={price} onChange={e=>setPrice(e.target.value.replace(/[^0-9.]/g,""))} inputMode="decimal" placeholder="1000" className={inputClass}/></Field></div>}
 {step===4&&<div className="mt-8 max-w-2xl"><h2 className="text-3xl text-deep">Payment</h2><p className="mt-2 text-forest/60">Your M-Pesa number is used for seller settlement and is never displayed publicly.</p><Field label="Seller handle"><input value={handle} onChange={e=>setHandle(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,""))} placeholder="myshop" className={inputClass}/></Field><Field label="M-Pesa number"><input value={paymentNumber} onChange={e=>setPaymentNumber(e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="0712345678" className={inputClass}/></Field>{!user&&<div className="mt-5 rounded-2xl bg-goldsoft/50 p-5"><p className="font-extrabold text-deep">Seller access</p><p className="mt-1 text-sm text-forest/65">Verify your seller identity once. The product Magic Link itself will be displayed on screen after publishing.</p>{!magicSent?<><input value={identity} onChange={e=>setIdentity(e.target.value)} placeholder="Email or phone number" className={inputClass+" mt-4"}/><button disabled={busy} onClick={sendMagic} className={btnClass("deep","md","mt-3 w-full")}>{busy?"Creating access…":"Verify Seller Access"}</button></>:<p className="mt-4 rounded-xl bg-white p-4 text-sm">Seller access request created. Open your existing verification link if required, then return to Sell Today.</p>}</div>}</div>}
 {step===5&&<div className="mt-8"><h2 className="text-3xl text-deep">Publish & Get Your Link</h2><p className="mt-2 text-forest/60">After publishing, your Magic Link will appear directly on this screen with a Copy Magic Link button. It will not be sent automatically by email or SMS.</p><button disabled={busy} onClick={publish} className={btnClass("gold","xl","mt-6 w-full")}>{busy?"Publishing…":"Create Product & Display Magic Link"}<Icon name="arrowRight" className="h-5 w-5"/></button></div>}
 {error&&<div className="mt-6 rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}<div className="mt-8 flex justify-between border-t border-forest/10 pt-6"><button type="button" disabled={step===1||busy} onClick={()=>{setError("");setStep(s=>s-1)}} className={btnClass("outline","md")}>Back</button>{step<4&&<button type="button" onClick={next} className={btnClass("gold","lg")}>Continue<Icon name="arrowRight" className="h-5 w-5"/></button>}{step===4&&user&&<button type="button" onClick={save} disabled={busy} className={btnClass("gold","lg")}>Continue<Icon name="arrowRight" className="h-5 w-5"/></button>}</div></div><p className="mx-auto mt-5 max-w-2xl text-center text-xs font-semibold text-forest/45">Secure setup. Your payment details are encrypted and never displayed publicly.</p></Container></section>;
}